# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

font_family Fira Code SemiBold
font_size 16.0
bold_font auto
italic_font auto
bold_italic_font auto

background_opacity 0.7
confirm_os_window_close 0

# change to x11 or wayland or leave auto
linux_display_server auto

scrollback_lines 2000
wheel_scroll_min_lines 1

enable_audio_bell no

window_padding_width 4

selection_foreground none
selection_background none

foreground         #FAEAEB
background         #120000
cursor             #FAEAEB

active_tab_foreground     #120000
active_tab_background     #FAEAEB
inactive_tab_foreground   #FAEAEB
inactive_tab_background   #120000

active_border_color   #FAEAEB
inactive_border_color #120000
bell_border_color     #5F4B4C

color0      #120000
color1		#5F4B4C
color2		#85575C
color3		#7A6163
color4		#AF8B8E
color5		#AF8E90
color6		#B59295
color7		#F0D8DA
color8		#A89899
color9		#7E6465
color10		#B1747A
color11		#A28283
color12		#E9B9BD
color13		#EABDC0
color14		#F1C3C6
color15		#F0D8DA
