# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(120000)
$foreground = rgb(FAEAEB)
$color0 = rgb(120000)
$color1 = rgb(5F4B4C)
$color2 = rgb(85575C)
$color3 = rgb(7A6163)
$color4 = rgb(AF8B8E)
$color5 = rgb(AF8E90)
$color6 = rgb(B59295)
$color7 = rgb(F0D8DA)
$color8 = rgb(A89899)
$color9 = rgb(7E6465)
$color10 = rgb(B1747A)
$color11 = rgb(A28283)
$color12 = rgb(E9B9BD)
$color13 = rgb(EABDC0)
$color14 = rgb(F1C3C6)
$color15 = rgb(F0D8DA)
